### ISSUE TITLE
Kotlin 1.4 support

### ISSUE THREAD

**Issue by dgomolka** [korlibs/klock#101]
Is it something we can look forward to?

**Comment by soywiz** [comment]
Unless someone else makes a PR, I will probably wait for M2. Since it is a prerelease why don't you compile it by yourself? Do you need it to be uploaded at bintray/jcenter?

**Comment by dankito** [comment]
Saw there's some activity going on on branch kotlin-1.4.0.

Do you already have an approximate time table when Kotlin 1.4.0 will be supported?

**Comment by soywiz** [comment]
This weekend. The main problem right now is that the current CI deploy doesn't support branches. I plan to change it to support several branches by using tags. My plan is to do it this weekend.

**Comment by dankito** [comment]
Perfect!

Thank you so much for your efforts!

**Comment by soywiz** [comment]
Hopefully `2.0.0-alpha-2` should support `Kotlin 1.4-M2`

**Comment by soywiz** [comment]
Feel free to reopen if required

**Comment by sksamuel** [comment]
Does klock 1.11 use features that are incompatible with Kotlin 1.4?
In other words, can I safely release a library that uses klock 1.11 and have that work with Kotlin 1.4 ?

**Comment by soywiz** [comment]
Kotlin 1.12 released supporting Kotlin 1.4
