### ISSUE TITLE
ISO8601 formats don't handle fractional seconds

### ISSUE THREAD

**Issue by j0bro** [korlibs/klock#102]
Given a timestamp as a `DateTimeTz` value:

`timestamp.format(ISO8601.IsoDateTimeFormat(null, "YYYY-MM-DDThh:mm:ss.sssZ"))`

does not work since it wants to try to parse the fractional part as seconds.

**Comment by rwslinkman** [comment]
This also goes for the `DateTime` class.

**Comment by RezMike** [comment]
@j0bro, @rwslinkman, you need to use 'S' for fractional part:
`timestamp.format(ISO8601.IsoDateTimeFormat(null, "YYYY-MM-DDThh:mm:ss.SSSZ"))`

**Comment by j0bro** [comment]
I am afraid that is not the case. They should be lowercase and I inspected
the source, it is not even trying to parse the fraction. What happens is
that it tries to match it against the seconds part, which only succeeds if
one provides two s's after the period, otherwise it fails.

Op zo 19 apr. 2020 17:10 schreef Mikhail Reznichenko <
notifications@github.com>:

**Comment by RezMike** [comment]
@j0bro it works correctly with 'S' for milliseconds
![image](https://user-images.githubusercontent.com/19624167/79692340-c88ef380-828e-11ea-9f35-4c88bc015f78.png)

**Comment by RezMike** [comment]
Ah, I missed your mention about ISO8601 format, sorry. For ISO8601 it's a bug indeed

**Comment by RezMike** [comment]
@j0bro I fixed this bug in #106

**Comment by RezMike** [comment]
@rwslinkman you should use `S` for milliseconds with `DateTime` formatting/parsing:
`PatternDateFormat("dd MMM yyyy HH:mm:ss.SSS")`
If you still need to use `s` for milliseconds, please create a new issue.
