### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException - Invalid dayOfYear=-265, isLeap=false

### ISSUE THREAD

**Issue by mikezliu** [korlibs/klock#103]
I'm seeing this crash in production for some users. I am not sure how to repro it yet, since I didn't log the input date.

```
Fatal Exception: java.lang.IllegalStateException - Invalid dayOfYear=-265, isLeap=false
```

Stacktrace:

```
com.soywiz.klock.DateTime$Companion.getDatePart$klock_release (DateTime.java:231)
com.soywiz.klock.DateTime.getMonth1-impl (DateTime.java:264)
com.soywiz.klock.DateTime.getMonth0-impl (DateTime.java:262)
com.soywiz.klock.PatternDateFormat.format (PatternDateFormat.java:124)
```

It happens in this line in DateTime:

`val month = Month.fromDayOfYear(dayOfYear, isLeap) ?: error("Invalid dayOfYear=$dayOfYear, isLeap=$isLeap")`

My usage:

```
ThreadLocalFormatters.dateFormatMonthDayYear.get()!!.format(dateTime.local)
```

```
object ThreadLocalFormatters {
  val dateFormatMonthDayYear: ThreadLocal<DateFormat> = object : ThreadLocal<DateFormat>() {
        override fun initialValue(): DateFormat {
            return PatternDateFormat("MMM d, yyyy", KlockLocale.english)
        }
    }
}
```

**Comment by RezMike** [comment]
@mikezliu, do you have an error message?

**Comment by viteqqq** [comment]
I'm seeing this quite a lot as well, like 16 times in the last week on several different devices according to play console reports.

**Comment by mikezliu** [comment]
I'm using:
Klock 1.9.1
Kotlin 1.3.72

**Comment by RezMike** [comment]
I can't help here without knowing the value of `dateTime.local` (and maybe `dateTime`). This error may be caused by OS or by something else, not by the klock library. I don't know how to reproduce this error. Maybe @soywiz can help.

**Comment by mikezliu** [comment]
I'm guessing it's some issue to do with leap year (2020)? I will try write a unit test to brute force test out each day of this year going back. There's a lot of logic in com.soywiz.klock.Month that calculates number of days in leap year, perhaps the issue is in there.

**Comment by mikezliu** [comment]
I wrote some unit tests and it seems to happen when formatting an invalid date, but I'm not sure if this is what caused the error in the original report

```
val now = DateTime.now()
val pattern = PatternDateFormat("MMM d, yyyy", KlockLocale.english)
pattern.format((now - 781693.days).local)
```

```
Invalid dayOfYear=-326, isLeap=false
java.lang.IllegalStateException: Invalid dayOfYear=-326, isLeap=false
	at com.soywiz.klock.DateTime$Companion.getDatePart$klock(DateTime.kt:231)
	at com.soywiz.klock.DateTime.getMonth1-impl(DateTime.kt:264)
	at com.soywiz.klock.DateTime.getMonth0-impl(DateTime.kt:262)
	at com.soywiz.klock.PatternDateFormat.format(PatternDateFormat.kt:126)
```

**Comment by RezMike** [comment]
Yeah, I understand that invalid dates cause this error. But was the original error caused by a valid date? If yes, then we should look for a bug in one part of the `klock` library. If no, then a bug may be in other parts of the library or in the developer's code.

**Comment by soywiz** [comment]
The library just support dates from the year 0 onwards. Is it possible for someone to pick or select dates below that? I can try to generate dates from year 0 until today and check if there are some cases producing strange values. Maybe negative values on the time could lead to the whole number being negative? You don't have by chance more info by now, right?
