### ISSUE TITLE
Versions list

### ISSUE THREAD

**Issue by hovi** [korlibs/klock#104]
Hi,

I am trying to use this library in my multiplatform project, which runs on android, ios and javascript.
Having issues, that I need to have lots of version checks:
- Need to have library compiled at same kotlin versin as my code for native (1.3.71)
- Need to have library which has android minSDK 14 or lower (I see newer versions have 16).

Can you please update readme file with list of versions, their respective kotlin version used and android minSDK?
Or at least, how to find it in source per tag?
Also why is there requirement for min version of 16? I wanna know if I can still use in SDK 14.
Thanks!

**Comment by soywiz** [comment]
I guess we should use the minimum SDK as possible here. This library doesn't have fancy stuff requiring older versions so I guess that should be possible.
