### ISSUE TITLE
Crash on iOS Simulator

### ISSUE THREAD

**Issue by akavalera** [korlibs/klock#105]
Hi, first of all thanks for set of useful libraries for Kotlin Native!
In my KN project I found that iOS application crashes  when running on iPhone 5s, SE or iPad 2-4, Air 1-2 simulator. I checked on real device and everything is fine there. Application launches and crashes when loads libraries.

dyld: Symbol not found: _in6addr_linklocal_allv2routers
  Referenced from: /Users/A/Library/Developer/CoreSimulator/Devices/D9F24910-4C95-43AE-9D2E-A27970EBB224/data/Containers/Bundle/Application/20A55AA7-F3A3-439D-B4CA-EAE4E2C5F03D/B.app/Frameworks/C.framework/C
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib

I think that can be related to this import:
import platform.posix.* in nativePosixMain module

**Comment by soywiz** [comment]
As far as I know imports are a compile-time feature for symbol resolving, not sure if that affects there.
Can you try to compile Klock changing the * import with specific imports and see if that still happens to you?
Have you managed to solve this or it is still a problem?

**Comment by soywiz** [comment]
Closing this. Feel free to reopen if you have more information.
