### ISSUE TITLE
Kotest matchers

### ISSUE THREAD

**Issue by sksamuel** [korlibs/klock#107]
Is there somewhere we can mention in the docs that Kotest now supports matchers on klock types.

https://github.com/kotest/kotest/tree/master/kotest-assertions/kotest-assertions-klock
https://github.com/kotest/kotest/blob/master/doc/matchers.md

**Comment by soywiz** [comment]
Nice, thanks! :) I will add it to the Klock documentation here: https://korlibs.soywiz.com/klock/ and to the README

**Comment by soywiz** [comment]
Added a small text in the README and the documentation. You can propose changes:
* https://github.com/korlibs/klock/blob/master/README.md
* https://github.com/korlibs/korlibs.soywiz.com/blob/master/klock/index.md
