### ISSUE TITLE
Linux freezes when run runNativex64Linux

### ISSUE THREAD

**Issue by Kooostia16** [korlibs/klock#120]
When I'm trying to run runNativex64Linux, my PC freezes after some time.

**Comment by soywiz** [comment]
Looks more related to Kotlin/Native itself. It uses several threads for compiling, so might have sense that your computer freezes specially if you have few cores/threads available.
Why do you think this issue is related with Klock?

**Comment by Kooostia16** [comment]
Oh, I thought I've added issue to korlibs. Ok, I will check it.
