### ISSUE TITLE
Target linuxArm64

### ISSUE THREAD

**Issue by clhols** [korlibs/klock#130]
I am trying to build for the Raspberry Pi and therefore setting target to linuxArm64.

But that gives me build time error:
Execution failed for task ':compileKotlinLinuxArm64'.
> Could not resolve all files for configuration ':linuxArm64CompileKlibraries'.
   > Could not resolve com.soywiz.korlibs.klock:klock:1.11.14.
     Required by:
         project :
      > Unable to find a matching variant of com.soywiz.korlibs.klock:klock:1.11.14:

**Comment by soywiz** [comment]
If we can crosscompile this or having an arm64 on github actions we could support this

**Comment by clhols** [comment]
The Kotlin docs say: "Linux MIPS targets (linuxMips32 and linuxMipsel32) require a Linux host. Other Linux targets can be built on any supported host;"

**Comment by soywiz** [comment]
https://github.com/korlibs/klock/commit/9c0c4e3c3acceb352c8b09bbc558af5d97926e84
