### ISSUE TITLE
ISO 8601 with Timezone

### ISSUE THREAD

**Issue by danielgruber** [korlibs/klock#134]
Hi Soywiz,
How easy would it be to support ISO 8601 with Timezone, e.g. 
2011-12-03T10:15:30+01:00 or
2011-12-03T10:15:30+0100

I would also be willing to implement this, but am unsure how to do it right 👍

**Comment by soywiz** [comment]
Isn't this one? https://github.com/korlibs/klock/blob/f5c4f05a5a875da7d06a919ba8e8f1263989bc12/klock/src/commonMain/kotlin/com/soywiz/klock/DateFormat.kt#L11

**Comment by danielgruber** [comment]
I think the Z does only work fit ISO8601 Git UTC or does it also parse +01:00 or +0100? In my Tests lastly it didn’t work.

**Comment by alexwhb** [comment]
I'm having this issue on iOS only... trying to format like this: `YYYY-MM-dd'T'HH:mm:ss'Z` and I get output like this: 2021-09-DDT22:23:18Z
On the android side this does work though for some reason.
