### ISSUE TITLE
Release on Maven Central?

### ISSUE THREAD

**Issue by DanySK** [korlibs/klock#138]
Hi,
is there any chance that klock gets released on Maven Central? It is currently being used by Kotest, which is widely used (in many of my projects as well) and it is released on Central. However, since they updated, it is now impossible to use the library for projects that need to use Central alone.
See kotest/kotest#1630.

In case, I can help simplifying the process, I wrote a plugin to reduce the burden of publishing towards Central.

**Comment by soywiz** [comment]
Related issue https://github.com/korlibs/korte/issues/13

**Comment by soywiz** [comment]
Released Klock 2.0.7 on central
