### ISSUE TITLE
ISO8601.DATETIME_UTC_COMPLETE

### ISSUE THREAD

**Issue by hardysim** [korlibs/klock#139]
Can we get a constant for the ISO8601-Instant-String (e.g. `2020-08-20T08:17:56Z`). There's already `ISO8601.DATETIME_COMPLETE` which comes close but is missing the `Z` at the end. And there is also no constant with the fraction-variant (e.g. `2020-08-20T08:17:56.123Z`).

I've added the following extensions to my project which would nicely fit into the library itself:

```kotlin
val DATETIME_UTC_COMPLETE = ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmssZ", "YYYY-MM-DDThh:mm:ssZ")
val DATETIME_UTC_COMPLETE_FRACTION = ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmss.sssZ", "YYYY-MM-DDThh:mm:ss.sssZ")
```

Or am I missing some constants? I've found `DateFormat.FORMAT2` which is the same but not for UTC. I'd be happy to add a PR as well if this is approved.

**Comment by soywiz** [comment]
Feel free to make a PR

**Comment by hardysim** [comment]
Reading deeper it seems that the number of fraction-digits is variable (from 0 to 9).

- https://stackoverflow.com/questions/25842840/representing-fraction-of-second-with-iso-86012004/25876314#25876314
- https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT

Looking at `java.time.format.DateTimeFormatter.ISO_INSTANT` it seems that this is smart enough to understand any length and just works. I think to match that (I need to talk to a java-server which outputs  6 digits) our `IsoDateTimeFormat` needs to be adjusted?

@soywiz I don't know how to do this? Adding a new format is fine but have the library understand a variable digit length is not. Can you help?
