### ISSUE TITLE
Deployment to Maven Central

### ISSUE THREAD

**Issue by jschneider** [korlibs/klock#159]
Since JFrog is shutting down JCenter and Bintray (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) it would be helpful to have klock deployed to Maven Central.

In April these repositories will start to become unavailable and shut down finally on May 1st.

**Comment by soywiz** [comment]
Fuck :)

**Comment by soywiz** [comment]
Main issue for all the libraries https://github.com/korlibs/korge-next/issues/153

**Comment by soywiz** [comment]
2.0.7 released on Central: https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock/2.0.7/
