### ISSUE TITLE
Android java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by alexandru-g** [korlibs/klock#163]
I'm trying to use this library in a Kotlin Multiplatform app:

- `implementation("com.soywiz.korlibs.klock:klock:1.10.3")` in the common module
- `implementation("com.soywiz.korlibs.klock:klock-android:1.10.3")` in the Android module
- `fun unlockedAt(): String = (DateTime.now() + timestamp.seconds).formatUnlockable()` defined in the common module

The following exception is thrown when `unlockedAt()` is called in the Android module:
`java.lang.NoSuchMethodError: No virtual method now-TZYpA4o()D in class Lcom/soywiz/klock/DateTime$Companion; or its super classes (declaration of 'com.soywiz.klock.DateTime$Companion' appears in /data/data/package_name/code_cache/.overlay/base.apk/classes21.dex)`

What am I doing wrong? Thank you!

**Comment by soywiz** [comment]
Latest version is `2.0.6`, the one you included is pretty old and unsupported. Can you try the last one?

**Comment by alexandru-g** [comment]
That seems to be it, I never thought to check the version, thanks.
You may want to update the documentation: https://korlibs.soywiz.com/klock/#buildgradlekts

**Comment by soywiz** [comment]
Thanks for your suggestion. Updated versions here: https://github.com/korlibs/korlibs.soywiz.com/commit/3bba100f8874ff8a2c0f0cf3e1152f7a9bd940bd
