### ISSUE TITLE
How to handle daylight saving time?

### ISSUE THREAD

**Issue by ln-12** [korlibs/klock#166]
After switching from winter time to summer time (or daylight saving time) the offset is changed by 1 hour. For example, if I want to use `DateTimeTz.utc(DateTime.now(), OFFSET)`, what should I put in for `OFFSET`? In winter it is `1.hours`, while now in summer it is `2.hours`. When executing it with the winter offset it obviously gives me the wrong time of `Fri, 09 Apr 2021 10:14:27 GMT+0100` where it should be `Fri, 09 Apr 2021 11:14:27 GMT+0200`. So in my case I need to know if `CET` or `CEST` has to be applied. I want to get the tome in `CET`, no matter what timezone the user hat set on his device.

I found that the [java class provides a method](https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#useDaylightTime()) for this.

**Comment by soywiz** [comment]
You can get the specific offset offset for your current TimeZone for a specific time with this:

https://github.com/korlibs/klock/blob/a7a4908e8bb6847ae69d53e8e1f9d072a8054bae/klock/src/commonMain/kotlin/com/soywiz/klock/TimezoneOffset.kt#L55

That means that if you request the offset for a winter date it will return +01:00, while if you request it for a summer one, it will return +02:00.

Klock doesn't have baked TimeZones. And it only interacts with the operating system with the current UTC time, and the offset for a specific date.

**Comment by ln-12** [comment]
I see, thank you for the help! :)
