### ISSUE TITLE
Legacy JS support removed - intentional?

### ISSUE THREAD

**Issue by jpd236** [korlibs/klock#170]
klock 2.1.1 appears to no longer include support for Kotlin/JS's legacy compiler. I'm guessing this is due to this commit:

https://github.com/korlibs/easy-kotlin-mpp-gradle-plugin/commit/f84b257fe8582e73783868d3cd88ce2e168e889e

I wanted to ask what the reasoning was behind this change. My project (https://github.com/jpd236/kotwords) still uses the legacy compiler; the IR compiler is still pretty rough around the edges from my testing - it's explicitly marked as an alpha in the official docs - and doesn't seem to be a trivial change. The docs [here](https://kotlinlang.org/docs/whatsnew15.html#frameworks-and-libraries-for-the-ir-compiler) recommend that libraries compile to both. Wouldn't it make sense here to release both versions until IR becomes more stable and prevalent?

**Comment by soywiz** [comment]
I removed it intentionally. But I can enable it again

**Comment by soywiz** [comment]
In theory if everything goes well 0.15.3 should include BOTH artifacts: https://github.com/korlibs/klock/actions/runs/874689849
I'm closing the issue. Feel free to reopen if you find some issues with this

**Comment by jschneider** [comment]
It seems that at least 2.3.1 does *not* contain the legacy version. At least Gradle is complaining in my project.

**Comment by jschneider** [comment]
It seems that 2.2.2 contains the version for legacy backend, 2.3.0 is the fist version without

**Comment by soywiz** [comment]
@jschneider no new additions on 2.3.0. The release is there because was triggered in korge-next for a consistent release to save me time on releases:
https://github.com/korlibs/korge-next

You can safely use 2.2.2 that should be binary compatible with all Kotlin 1.5.x versions.
