### ISSUE TITLE
Doesn't have release version klock:klock-android

### ISSUE THREAD

**Issue by AlexanderMikulich** [korlibs/klock#172]
Working with com.soywiz.korlibs.klock:klock-android. When I use debug, it works. When i tried to build internal/release version i faced with problem 

`Execution failed for task ':app:checkInternalAarMetadata'.
> Could not resolve all files for configuration ':app:internalRuntimeClasspath'.
   > Could not resolve com.soywiz.korlibs.klock:klock-android:2.0.0.
     Required by:
         project :app
      > No matching variant of com.soywiz.korlibs.klock:klock-android:2.0.0 was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'internal', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'debugApiElements-published' capability com.soywiz.korlibs.klock:klock-android:2.0.0 declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'internal'
          - Variant 'debugRuntimeElements-published' capability com.soywiz.korlibs.klock:klock-android:2.0.0 declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'internal'
          - Variant '***ApiElements-published' capability com.soywiz.korlibs.klock:klock-android:2.0.0 declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value '***' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'internal'
          - Variant '***RuntimeElements-published' capability com.soywiz.korlibs.klock:klock-android:2.0.0 declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value '***' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'internal'`

As I see we have only debug lib version
![image](https://user-images.githubusercontent.com/53609902/119709651-1f89d380-be66-11eb-9a2f-6bf77dec19e0.png)

I can add  matchingFallbacks but could you add release version?

ps. com.soywiz.korlibs.klock:klock-jvm doesn't have such problem

**Comment by soywiz** [comment]
I'm assuming this is not an issue anymore: https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock-android/2.4.7/
