### ISSUE TITLE
Missing watchosX64  artifacts in latest version  2.4.12

### ISSUE THREAD

**Issue by benchuk** [korlibs/klock#183]
Trying to compile klock version 2.4.12 for WatchOS simulator fail as maven missing these artifacts.

**Comment by benchuk** [comment]
please see suggested fix here:
https://github.com/korlibs/easy-kotlin-mpp-gradle-plugin/issues/17

**Comment by benchuk** [comment]
create pull request to fix klock Deploy flow to create watchosx64 artifacts #185

**Comment by soywiz** [comment]
Merged and triggered https://github.com/korlibs/klock/releases/tag/v2.4.13 let me know if it works now.

**Comment by benchuk** [comment]
Is it published to maven?

**Comment by soywiz** [comment]
https://github.com/korlibs/klock/actions/runs/1774603883 it seems to have finished. Central might take 15 minutes to be available

**Comment by benchuk** [comment]
Ok, great 👍

**Comment by benchuk** [comment]
Still no 2.4.13 - build failed?

**Comment by soywiz** [comment]
@benchuk https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock/2.4.13/

**Comment by benchuk** [comment]
Ok - now it works perfectly! Thanks 🙏
