### ISSUE TITLE
Occasional bug in date formatter

### ISSUE THREAD

**Issue by robertfmurdock** [korlibs/klock#187]
Seeing inconsistent roundtrips when using DATETIME_UTC_COMPLETE_FRACTION

Example: DateTime(1644075138096) becomes 2022-02-05T15:32:18.960Z (which is incorrect).

Tested with 2.4.13

**Comment by soywiz** [comment]
What would you expect to be the right result?

**Comment by robertfmurdock** [comment]
The milliseconds position is wrong… needs a leading zero to go both ways

If you create it, convert it, and convert it back you see the date time isn’t equal to the original

**Comment by soywiz** [comment]
Then you would expect `2022-02-05T15:32:18.096Z`?

**Comment by robertfmurdock** [comment]
Yeah
