### ISSUE TITLE
Chinese Locale still use "am/pm"

### ISSUE THREAD

**Issue by xszqxszq** [korlibs/klock#191]
In Chinese, "am" and "pm" should be "上午" and "下午", but the results of `ChineseKlockLocale.formatDateTimeMedium.format()` `ChineseKlockLocale.formatDateTimeShort.format()` still use "am" and "pm".
And in `testChineseLocale()` from KlockLocaleTest.kt, "2019年3月13日 pm9:36:45""2019/3/13 pm9:36" are wrong too.

Btw I find that there is a `ChineseKlockLocale.h12Marker` which has the correct word for "am" and "pm", but it seems that it is not used.

**Comment by soywiz** [comment]
Notes:

Here's the offending line: https://github.com/korlibs/klock/blob/9bbef7aca8018d7b64d971a777d03b9bac07686e/klock/src/commonMain/kotlin/com/soywiz/klock/PatternDateFormat.kt#L186

It should be something like: `locale.h12Marker[(utc.hours < 12).toInt()]`

Also the english h12Marker: https://github.com/korlibs/klock/blob/9bbef7aca8018d7b64d971a777d03b9bac07686e/klock/src/commonMain/kotlin/com/soywiz/klock/KlockLocale.kt#L66

seems to be wrong too
