### ISSUE TITLE
New binaries for Kotlin 1.3.20

### ISSUE THREAD

**Issue by benasher44** [korlibs/klock#22]
Hi there! I had klock working with Kotlin 1.3.11, but now with 1.3.20, I'm getting build errors. I'm assuming (correct me if I'm wrong) that's because something about binarty compatibility changed with 1.3.20. If that make sense, could you do another release for Kotlin 1.3.20? Thanks! (specifically trying to build for iOS arm64/x64)

**Comment by soywiz** [comment]
Should be fixed with #23 Also I have published 1.1.0: https://bintray.com/soywiz/soywiz/klock/1.1.0
