### ISSUE TITLE
Support optional format parts

### ISSUE THREAD

**Issue by serebit** [korlibs/klock#27]
In my usage of Klock, I need it to parse a timestamp that may or may not have the milliseconds field present. Having support for it in the formatter would be a great help.

**Comment by soywiz** [comment]
How would you do (represent it in the formatter) this in Java or in other languages?

**Comment by serebit** [comment]
Could take inspiration from regex and do something like `(optional)?` in the format string

**Comment by soywiz** [comment]
This is my proposal:

```kotlin
val format = PatternDateFormat("YYYY[-MM[-dd]]").withOptional()
assertEquals("2019-01-01", format.parse("2019").toString(format))
assertEquals("2019-09-01", format.parse("2019-09").toString(format))
assertEquals("2019-09-03", format.parse("2019-09-03").toString(format))
```

**Comment by serebit** [comment]
Yep, that looks fine to me.
