### ISSUE TITLE
Wrong gradle import documentation

### ISSUE THREAD

**Issue by andob** [korlibs/klock#34]
Hello, thanks for developing this amazing library..

The documentation of "Usage with gradle" from [https://korlibs.soywiz.com/klock/](here) and [https://github.com/korlibs/klock/blob/master/README.md](here) is wrong and confusing. Please correct it:

```
dependencies {
    // For multiplatform projects, since klock is published without metadata
    implementation "com.soywiz:klock-metadata:$klockVersion" // Common 
    implementation "com.soywiz:klock-jvm:$klockVersion" // JVM
    implementation "com.soywiz:klock-js:$klockVersion" // JavaScript
    implementation "com.soywiz:klock-android:$klockVersion" // Android
    implementation "com.soywiz:klock-iosx64:$libraryVersion" // iOS Simulator
    implementation "com.soywiz:klock-iosarm32:$libraryVersion" // Older iOS 32-bit devices
    implementation "com.soywiz:klock-iosarm64:$libraryVersion" // Newer iOS 64-bit devices
    implementation "com.soywiz:klock-macosx64:$libraryVersion" // MacOS
    implementation "com.soywiz:klock-linuxx64:$libraryVersion" // Linux x64
    implementation "com.soywiz:klock-mingwx64:$libraryVersion" // Windows x64
}
```

**Comment by soywiz** [comment]
Why do you think the Klock README is wrong?
You have to specify the platform for each artifact. So `implementation` in the global dependencies block shouldn't work as far as I know (unless I'm wrong).

**Comment by gschmauch** [comment]
Hi Soywiz,

Well i'm using IntelliJ IDEA to learn Kotlin, first i had to update the version avec Gradle, the default version was 4.X so i switched to 5.2.1

Still didn't work, until i changed "jvmMainApi" to "Implementation" and now i can use your library.
