### ISSUE TITLE
nowLocal() not works on Android ?

### ISSUE THREAD

**Issue by irgaly** [korlibs/klock#38]
Android 8.0.0, Klock 1.1.1

System timezone is `JST Asia/Tokyo (+9:00)`

In this situation, at 2019-04-15 20:14:30 (JST), `DateTime.now()`, `DateTimeTz.nowLocal()` results this. This might be wrong...?

![image](https://user-images.githubusercontent.com/1311446/56128793-9bdd3780-5fbb-11e9-8919-8a694f991ff6.png)

**Comment by irgaly** [comment]
I updated Klock 1.5.0. gradle: `implementation "com.soywiz.korlibs.klock:klock:1.5.0"`
It has still wrong result.

![image](https://user-images.githubusercontent.com/1311446/60586965-3d5f7280-9dce-11e9-8959-46e19093b50c.png)

**Comment by irgaly** [comment]
I'm wating next version :)

**Comment by soywiz** [comment]
This should be fixed. Please reopen if necessary.

![Uploading Screenshot 2019-09-20 at 12.43.41.png…]()
