### ISSUE TITLE
Separate classes for Date and Time

### ISSUE THREAD

**Issue by gnefedev** [korlibs/klock#42]
It will be grate to have classes for truncated date (year+month+day) and pure time (hour+minute+second)

**Comment by irgaly** [comment]
I think almost same things.

In my project, I finally created YearMonthDay (that has year:Int, month: Int, day: Int) class, and LocalTime (that has hour: Int, minute: Int, second: Int, milliseconds: Int).

**Comment by soywiz** [comment]
Included in Klock 1.7.0:
https://github.com/korlibs/klock/blob/master/klock/src/commonMain/kotlin/com/soywiz/klock/Date.kt
https://github.com/korlibs/klock/blob/master/klock/src/commonMain/kotlin/com/soywiz/klock/Time.kt
