### ISSUE TITLE
Question: How do you manage to build your libraries for all platforms?

### ISSUE THREAD

**Issue by luca992** [korlibs/klock#43]
@soywiz 
Not sure if this is the best place to ask, but maybe others are interested too. 

As far as I have seen, you are the only person actually creating libraries for all platform's that Kotlin multiplatform supports. I am just curious, what is your setup to build and publish your libraries... This isn't as hard as before now that kotlin 1.3.30 can ["In addition to that, Windows and macOS users can cross-compile their Kotlin/Native programs to Linux x86-64, arm32, as well as Android and Raspberry PI devices."](https://blog.jetbrains.com/kotlin/2019/04/kotlin-1-3-30-released/)

But still, you need to at least switch between windows and mac to build and publish.  How are you managing this (in a timely manner)? What I am most curious about is if you have an automated way to do this... or are you just using virtual desktops or multiple computers?

**Comment by soywiz** [comment]
Y just use mac:
https://soywiz.com/building-win-linux-kotlin-native-on-mac/
https://forum.soywiz.com/topic/7/updated-soywiz-kotlin-native-win-docker-image
https://github.com/korlibs/klock/blob/master/gradlew_win
