### ISSUE TITLE
Unresolved reference DateTime 

### ISSUE THREAD

**Issue by sathishsr** [korlibs/klock#47]
**Tried following the existing closed issue,https://github.com/korlibs/klock/issues/16#issue-389826080, BUT NEGATIVE.**

I am using klock for one of my multiplatform project and I ended up with this issue
**SharedCode/src/commonMain/kotlin/common.kt: (3, 25): Unresolved reference: DateTime**

My gradle versions:
Gradle : 5.3.1
Kotlin: 1.3.20
klock: 1.4.0

My gradle files looks as below:
kotlin {

    targets {
        final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos") \
                              ? presets.iosArm64 : presets.iosX64

        fromPreset(iOSTarget, 'iOS') {
            compilations.main.outputKinds('FRAMEWORK')
        }

        fromPreset(presets.jvm, 'android')
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation "com.soywiz:klock-metadata:${klockVersion}"
                implementation "org.jetbrains.kotlin:kotlin-stdlib-common:${kotlin_version}"
            }
        }
        commonTest {
            dependencies {
                implementation "org.jetbrains.kotlin:kotlin-test-common:${kotlin_version}"
                implementation "org.jetbrains.kotlin:kotlin-test-annotations-common:${kotlin_version}"
            }
        }
        androidMain {
            dependencies {
                implementation "com.soywiz:klock-android:${klockVersion}"
                implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${kotlin_version}"
            }
        }
        jvmTest {
            dependencies {
                implementation "org.jetbrains.kotlin:kotlin-test:${kotlin_version}"
                implementation "org.jetbrains.kotlin:kotlin-test-junit:${kotlin_version}"
            }
        }
        iosMain {
            dependencies{
                implementation 'com.soywiz:klock-iosarm32:1.2.0'
                implementation 'com.soywiz:klock-iosarm64:1.2.0'
                implementation 'com.soywiz:klock-iosx64:1.2.0'
            }
        }
        iosTest {
        }
        iosArm64Main {
            dependsOn iosMain
        }
        iosX64Main {
            dependsOn iosMain
        }

    }
}

**Comment by soywiz** [comment]
With latest version you are required to add `enableFeaturePreview('GRADLE_METADATA')` at your `settings.gradle`.
With that you won't need to add implementation for all the targets. Also now klock is available at jcenter and its group has changed.

This should work:

### `build.gradle`

```groovy
def klockVersion = "1.4.0"

repositories {
    jcenter()
}

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation "com.soywiz.korlibs.klock:klock:$klockVersion" // Common 
            }
        }
    }
}
```

### `settings.gradle`

```groovy
enableFeaturePreview('GRADLE_METADATA')
```

**Comment by georgeherby** [comment]
Ah, this explains the issues I have been having. Might be worth updating the README for this as i followed that using klock-metadata for common with all sorts of issues.
