### ISSUE TITLE
Cannot import the dependency

### ISSUE THREAD

**Issue by avjiang** [korlibs/klock#50]
Hi, i am new to the Kotlin Multiplatform, and found this amazing library. 

I am having problem to import the dependency into my common.kt file

here is my build.gradle file 

    def klockVersion = "1.4.0"

    repositories {
       jcenter()
    }

    kotlin {
      targets {
        final def iOSTarget = presets.iosArm64

        fromPreset(iOSTarget, 'iOS') {
            binaries {
                framework('SharedCode')
            }
        }

        fromPreset(presets.jvm, 'android')
    }

    sourceSets {
        commonMain {
            dependencies {
                api 'org.jetbrains.kotlin:kotlin-stdlib-common'
                implementation 'com.soywiz.korlibs.klock:klock:1.4.0'
            }
        }

        androidMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib'
        }
      }
    }
    
in my common.kt 

` import com.  // unresolved reference `

Can anyone guide me on this issue please ? 
Any guide given much appreciated. Thanks

**Comment by andylamax** [comment]
Do as below
```groovy
sourceSets {
    commonMain {
        dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib-common'
            implementation 'com.soywiz.korlibs.klock:klock-metadata:1.4.0' // instead of implementation 'com.soywiz.korlibs.klock:klock:1.4.0'
        }
    }

    androidMain.dependencies {
        api 'org.jetbrains.kotlin:kotlin-stdlib'
        implementation 'com.soywiz.korlibs.klock:klock-android:1.4.0' //add this line here
    }
  }
}
```
