### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by rdbatch02** [korlibs/klock#54]
Are there any plans to publish Klock's Kotlin/JS library on NPM? This would make it easier for JS libraries built using Kotlin/JS to be published on NPM and pull in Klock as a downstream dependency rather than re-packaging it alongside dependent code.

Currently, a Kotlin/JS publication that wants to leverage Klock as a dependency needs to include it as part of the artifact, rather than just a reference in its package.json file and allowing downstream users to install it as part of a standard `npm install` routine.

**Comment by sujithkris** [comment]
@rdbatch02: Did you update the `build.gradle` or any custom script to include `packages_imported` in js library?

I am doing `gradle assemble` which is creating the zip of js library (`build/lib/myproject-js-1.0.0.jar`), but the generated `package.json` have only npm dependencies` I specified in build.gradle. The generated `package.json` doesn't have dependencies like kotlin, klock etc. 

However I can see the build/js/packages/{project}/package.json have below lines

```
"kotlin": "file:/myproject/build/js/packages_imported/kotlin/1.4.10",
"korio-root-korio": "file:/myproject/build/js/packages_imported/korio-root-korio/1.10.2",
"klock-root-klock": "file:/myproject/build/js/packages_imported/klock-root-klock/1.10.3",
```
