### ISSUE TITLE
What is the right maven repository 

### ISSUE THREAD

**Issue by sith** [korlibs/klock#57]
I am trying to add klock maven repository to my maven project
` <repositories>
        <repository>
            <id>korlibs</id>
            <name>korlibs</name>
            <url>https://dl.bintray.com/korlibs/korlibs</url>
        </repository>
    </repositories>
`
My Intellij and cmd maven doesn't recognize it and shows an error.

**Comment by georgeherby** [comment]
See comment on issue #47 for new namenand path
https://github.com/korlibs/klock/issues/47#issuecomment-496484534

**Comment by sith** [comment]
I do not use gradle in my project - and the referred issue talks about gradle. Unless the resolution is to use jcenter repository

**Comment by soywiz** [comment]
The jvm artifact is one of these:

Bintray: https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/klock/klock-jvm/1.7.0/klock-jvm-1.7.0.jar
Jcenter: http://jcenter.bintray.com/com/soywiz/korlibs/klock/klock-jvm/1.7.0/klock-jvm-1.7.0.jar

group: com.soywiz.korlibs.klock
artifact-name: klock-jvm
artifact-version: 1.7.0

You can use either the bintray/korlibs/korlibs repo or jcenter. I'm closing this. Please reopen if necessary.
