### ISSUE TITLE
Add ISO8601 parser/formatter

### ISSUE THREAD

**Issue by Prototik** [korlibs/klock#6]
ISO8601 widely used format in many countries / systems / interchange formats / etc, so built-in support for it would be very nice.

**Comment by simonegiacomelli** [comment]
Yes, this would be handy!

**Comment by serebit** [comment]
Still waiting on this?

**Comment by soywiz** [comment]
Can you give feedback on this? https://github.com/korlibs/klock/commit/0353152bd80cc11719c287c2b0655996dc6e7b6e
This API would work for you?

**Comment by serebit** [comment]
Seems to be missing the extended formats, like `yyyy-MM-dd'T'HH:mm:ss.SSSXX` and `yyyy-MM-dd'T'HH:mm:ssXX`.
