### ISSUE TITLE
Incorrect Hour Displayed

### ISSUE THREAD

**Issue by napperley** [korlibs/klock#65]
After formatting a DateTime instance, and printing it out the hour is incorrect (exactly one hour behind):
``` Current Timestamp: 2019-09-30_00:42 ```

Here is the output after running the `date` command (on Linux) about two minutes later:
``` Mon Sep 30 13:44:39 NZDT 2019 ```

Used the following for converting a DateTime instance to text:
```kotlin
fun DateTime.toText(): String {
    // Use the following date time format: year-month-day hour:minute. Here is some example output: 2018-01-23_20:35.
    val pattern = "yyyy-MM-dd_HH:mm"
    return format(pattern)
}
```

**Comment by soywiz** [comment]
`DateTime` doesn't include the TimeZone. It is just an UTC instant.
Depending on how you get the DateTime instance you might get different results.
https://github.com/korlibs/klock/blob/13c9f5bcd0483f2ecad4bf16719ab58f76df4b78/klock/src/commonMain/kotlin/com/soywiz/klock/DateTime.kt#L182

You might want to call `DateTime.nowLocal()`, then you can use:
https://github.com/korlibs/klock/blob/master/klock/src/commonMain/kotlin/com/soywiz/klock/DateTimeTz.kt#L26
`DateTimeTz.local` or `DateTimeTz.utc`
