### ISSUE TITLE
minSdk 18 on Android

### ISSUE THREAD

**Issue by sky-filipeuva** [korlibs/klock#66]
Hey,

 is there any reason for the minSDK to be 18 for this specific lib ?

From perusing the source I did not find any, and the minSdk is set by the plugin across all your libraries on https://github.com/korlibs/easy-kotlin-mpp-gradle-plugin/blob/c163e5dcc870e79dae11620442cb73827b48c705/src/main/kotlin/com/soywiz/korlibs/targets/Android.kt#L13

We have a minSdk 16 requirement, want to confirm if it's fine to use this lib :)

**Comment by soywiz** [comment]
Which minimum version would you need?
AFAIK inSdk=16 is android 4.3

Android Name | Android Version | Usage Share
-- | -- | --
Pie | 9 | 10.4%
Nougat | 7.0, 7.1 | 19.2%↓
Marshmallow | 6.0 | 16.9%↓
Lollipop | 5.0, 5.1 | 14.5%↓
Oreo | 8.0, 8.1 | 28.3%↑
KitKat | 4.4 | 6.9%↓
Jelly Bean | 4.1.x, 4.2.x, 4.3.x | 3.2%↑
Ice Cream Sandwich | 4.0.3, 4.0.4 | 0.3%
Gingerbread | 2.3.3 to 2.3.7 | 0.3%↑

**Comment by sky-filipeuva** [comment]
https://developer.android.com/studio/releases/platforms#4.1

**Comment by soywiz** [comment]
Ok, I will try to change to 4.1 in the next version
