### ISSUE TITLE
JS publication has strange Kotlin version in package.json

### ISSUE THREAD

**Issue by lamba92** [korlibs/klock#68]
```json
{
  "main": "klock-root-klock.js",
  "dependencies": {
    "kotlin": "%%%KOTLIN_VERSION!!!"
  },
  "name": "klock-root-klock",
  "version": "0.0.0-VERSION"
}
```
Breaks multiplatform build when targetting Kotlin/JS and adding some dependencies from NPM using the 1.3.40+ Kotlin MPP/JS Gradle Plugins. ~~Of course if only importing from Maven the package.json does not comes into play and the issue is not present.~~ 
Trying to build the library even without NPM imports triggers the error as well.

[Here's a project to reproduce the bug](https://github.com/lamba92/KotlinJSKlockError).

**Comment by soywiz** [comment]
Can't reproduce:
```
npm i @korlibs/klock-locale
cat node_modules/@korlibs/klock-locale/package.json
```

...

```
  "dependencies": {
    "@korlibs/klock": "1.7.3",
    "kotlin": "1.3.50"
  },
```

**Comment by soywiz** [comment]
I have never used npm with Kotlin. I have tried this:
https://github.com/korlibs/klock/pull/70/commits/1677313206665faaaaedd9e88e083b1161e6b366

But maybe your usecase need the package.json to be part of the jar file? In which case I should process the package.json before generating the .jar file, or not including it at all?

**Comment by lamba92** [comment]
I actually just need to output a JS library from a multiplatform project that imports Klock. When doing so that error happens. The new Kotlin/JS plugin uses NPM and the `package.json` to fetch all dependencies that are both on Maven and NPM.

If you fork the project i linked above, just by trying to sync it with IntelliJ the error should happen. I think the problem may rely in the Maven publication, not the NPM one.

**Comment by lamba92** [comment]
> I think the problem may rely in the Maven publication, not the NPM one.

Indeed [here](https://bintray.com/korlibs/korlibs/klock#files/com%2Fsoywiz%2Fkorlibs%2Fklock%2Fklock-js%2F1.7.3) if you download ` klock-js-1.7.3.jar` you can easily check inside that the `package.json` file contains the token of the token `%%%KOTLIN_VERSION!!!`.

**Comment by lamba92** [comment]
May I ask when you plan to publish the fixed package?

**Comment by soywiz** [comment]
Once travis publishes it: https://travis-ci.org/korlibs/klock/builds/595570937
