### ISSUE TITLE
Test failure due to kinda broken dependencies

### ISSUE THREAD

**Issue by mschirmacher** [korlibs/klock#77]
Hello there,
in https://github.com/mschirmacher/wtf i prepared a small testcase to demonstrate the problem.

Long story short: `assertTrue(DateTime.nowUnixLong() is Long)` fails because klock brings its own `kotlin.js` hence we end up with two kotlin dependencies in the project and two declarations of `Long`.

You may find more information and discussion abput the problem mostly at the end of this 
thread on slack: https://kotlinlang.slack.com/archives/C0B8L3U69/p1574427184210500

**Comment by mschirmacher** [comment]
Ilya also suggested a workaround for this bug, which works for the test project above:
```
tasks.getByName("kotlinNpmInstall") {
    doLast {
        File("$buildDir/js/node_modules/klock-root-klock/node_modules").deleteRecursively()
    }
}
```

**Comment by soywiz** [comment]
Asked at slack. That looks a bit dirty. I'm not sure if totally remove the `package.json` and to not publish npm for newer versions.

**Comment by soywiz** [comment]
I'll use `peerDependencies` until Kotlin supports `package.json` publishing
