### ISSUE TITLE
Can't build against iOS using Kotlin 1.3.61, klock 1.8.3

### ISSUE THREAD

**Issue by mikezliu** [korlibs/klock#78]
I can't seem to build against iOS using Kotlin 1.3.61 

w: skipping /Users/.../.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-ios-iosarm64/1.2.4/.../ktor-client-ios.klib. The abi versions don't match. Expected '[17]', found '14'
w: The compiler versions don't match either. Expected '[]', found '1.3.50-release-11850'

I am using:
api "com.soywiz.korlibs.klock:klock:1.8.3"

**Comment by soywiz** [comment]
If you read the error, the module that is using an older Kotlin verson is `ktor-client-ios-iosarm64`. And in fact Ktor 1.2.4:
https://ktor.io/quickstart/migration/1.2.4.html
is compiled against 1.3.50-release-11850.

So this doesn't seems related  to klock

**Comment by mikezliu** [comment]
Ahh got it, I misread ktor as klock

**Comment by soywiz** [comment]
Alternatively if you want to use the ktor client without recompiling it, Klock `1.7.0` is compiled against Kotlin `1.3.50`.
