### ISSUE TITLE
Last version working for me is 1.7.0

### ISSUE THREAD

**Issue by jschneider** [korlibs/klock#80]
Hey,

I am trying to use klock in a multi platform project and a depending JS project.
This works fine with 1.7.0 dependencies. But updating to anything later results in different errors (related to the npm-install Gradle task).

I honestly don't know what might be wrong, I just wanted to ask if there have been any changes I don't understand. Especially because the version number mentioned on the home page is 1.7.0

**Comment by soywiz** [comment]
I'm going to totally delete the `package.json` for now since it is producing more problems than the one tries to solve.

Related issues:
* https://github.com/korlibs/klock/issues/54
* https://github.com/korlibs/klock/issues/77
* https://github.com/korlibs/klock/issues/68

**Comment by championswimmer** [comment]
Hi I get npm install errors with this still using kotlin `1.3.72`

Here is the sample project that gives the error, if you'd like to try. 
https://github.com/championswimmer/KMP_Sample_Project
