### ISSUE TITLE
PatternDateFormat fails to format 2019-04-26T19:00:00.0000000

### ISSUE THREAD

**Issue by schilumula** [korlibs/klock#81]
We are receiving the date in this format 2019-04-26T19:00:00.0000000 from MSAL API.

This is used to work before on 1.6.0 version. This fix fails this https://github.com/korlibs/klock/commit/1158341f0ede841bb045e94d294e953c5917f9d5#diff-067419ea4769cd82d17ebf8744b70f10L29.

This is the format we were using "yyyy-MM-dd'T'HH:mm:ss.SSSSSSS"

Can I expect a fix for this

**Comment by soywiz** [comment]
Fixed in 1.8.5

**Comment by schilumula** [comment]
Thanks
