### ISSUE TITLE
Formatting with sub-second precision broken?

### ISSUE THREAD

**Issue by johanneskraem3r** [korlibs/klock#84]
Formatting with sub-second precision seems to not work:

This:

```kotlin
val badUtc = DateTime(
date = Date(2020, 1, 4 ),
time = Time(2, 42,55, millisecond = 500)
val thisWorks = badUtc.format(ISO8601.DATETIME_COMPLETE)
val thisDoesNot = badUtc.format(ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmss,ss", "YYYY-MM-DDThh:mm:ss,ss"))
println("thisWorks=$thisWorks")
println("thisDoesNot=$thisDoesNot")
```

Prints this:

```
thisWorks=2020-01-04T02:42:55
thisDoesNot=2020-01-04T02:42:75,50
```

The error seems to be here: 

https://github.com/korlibs/klock/blob/f499c4a9f0590d7e23e9acdaf349d8e7deb9b162/klock/src/commonMain/kotlin/com/soywiz/klock/ISO8601.kt#L41

**Comment by johanneskraem3r** [comment]
Also, it would be nice to add support for 3 digits here. ms are not that uncommon...

**Comment by soywiz** [comment]
Have you tried "SS" uppercase?
https://github.com/korlibs/klock/blob/master/klock/src/commonMain/kotlin/com/soywiz/klock/PatternDateFormat.kt#L144

```kotlin
utc.format(ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmss,SS", "YYYY-MM-DDThh:mm:ss,SS"))
```

**Comment by johanneskraem3r** [comment]
Thanks for the answer ( and thanks for the lib!) 

I did check, and excuse the nitpicking, but that line that you posted will not work, as the current implementation of IsoDateTimeFormat ignores the uppercases 'S"s : 

`            val utc = DateTime.now()
            val thisWorks = utc.format(ISO8601.DATETIME_COMPLETE)
            val thisWorksToo = utc.format(DateFormat("yyyy-MM-dd__HH-mm-ss.SSS"))
            val thisDoesNot = utc.format(
                ISO8601.IsoDateTimeFormat("YYYYMMDDThhmmss,SS",
                    "YYYY-MM-DDThh:mm:ss,SS"))
            println("thisWorks(IsoDateTimeFormat,withoutMillis)=$thisWorks")
            println("thisWorksToo(DateFormat,withoutMillis)=$thisWorksToo")
            println("thisDoesNot(IsoDateTimeFormat, with Millis)=$thisDoesNot")`


prints: 

`
thisWorks(IsoDateTimeFormat,withoutMillis)=2020-01-16T17:59:08
thisWorksToo(DateFormat,withoutMillis)=2020-01-16__17-59-08.371 
thisDoesNot(IsoDateTimeFormat, with Millis)=2020-01-16T17:59:08,SS`

**Comment by soywiz** [comment]
Why are you using `IsoDateTimeFormat` instead of `PatternDateFormat`/`DateFormat`? I guess I missed that you were using that instead of the PatternDateFormat and placed the wrong.

**Comment by johanneskraem3r** [comment]
Boh, because I started out formatting ISO dates :) Does it matter ;-) ?

**Comment by soywiz** [comment]
I have reproduced the issue. I'm looking at it 👀

**Comment by johanneskraem3r** [comment]
Appreciated. It's a nitpick, I'm aware, but it cost me a bit of time, so I figured I'd share.

**Comment by soywiz** [comment]
Sorry I misunderstood it from the very beginning. Not a nitpicking but a bug. Still, the `ISO8601.IsoDateTimeFormat` shouldn't be used and should be internal.
`TIME_LOCAL_FRACTION0` and `TIME_UTC_FRACTION0` probably didn't work well
