### ISSUE TITLE
Make DateTimeTz Serializable

### ISSUE THREAD

**Issue by weliem** [korlibs/klock#86]
The standard Java Date object is actually Serializable, but in Klock DateTimeTz isn't.  Now that I replaced all my uses of Date with DateTimeTz in my application, I am running into issues because of this.

Could you make it Serializable?

**Comment by soywiz** [comment]
Can you verify this PR works for you? https://github.com/korlibs/klock/pull/87

**Comment by weliem** [comment]
Thank you very much!

**Comment by Skeptick** [comment]
Also, it would be nice to make Serializable WDateTime and WDate. Now they cannot be used in Parcelable classes on Android.

**Comment by soywiz** [comment]
@Skeptick Check if https://github.com/korlibs/klock/pull/114 works for you
