### ISSUE TITLE
Compatibility with Kotlin 1.3.70

### ISSUE THREAD

**Issue by PerrigoGames** [korlibs/klock#91]
Attempting to build the current 1.10.0 version of klock in a Multiplatform setting causes the iOS library to be skipped due to an unexpected abi version.

`> Task :shared:compileKotlinIos FAILED
w: skipping /Users/corey/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.klock/klock-iosx64/1.10.0/aa48e4992242cc06e8d749eafad3e3f9ba26c69e/klock.klib. The abi versions don't match. Expected '[17]', found '22'
w: The compiler versions don't match either. Expected '[]', found '1.3.70-release'
e: Could not find "/Users/corey/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.klock/klock-iosx64/1.10.0/aa48e4992242cc06e8d749eafad3e3f9ba26c69e/klock.klib" in [/Users/corey/Development/kotlin/Life4Trials, /Users/corey/.konan/klib, /Users/corey/.konan/kotlin-native-macos-1.3.61/klib/common, /Users/corey/.konan/kotlin-native-macos-1.3.61/klib/platform/ios_x64].`

I've tried changing the compiler version back to 1.3.61 via setting the proper version in my Gradle files, and by reinstalling the 1.3.61 version of the Kotlin plugin without much luck, but that's a separate issue.

**Comment by soywiz** [comment]
The error says that it expects 17 (1.3.61), but found 22 (1.3.70). Also I'm using 1.10.0 successfully on other projects with Kotlin 1.3.70. Are you sure your configuration is right?

**Comment by PerrigoGames** [comment]
This is what I have in my build scripts as of right now:

Dependencies.kt

```
object Versions {
    val min_sdk = 18
    val target_sdk = 28
    val compile_sdk = 28

    val kotlin = "1.3.61"
    val klock = "1.10.0"
    ...
}

object Deps {
    val klock = "com.soywiz.korlibs.klock:klock:${Versions.klock}"
    ...
}
```

build.gradle.kts (shared)
```
...
kotlin {
    android()
    //Revert to just ios() when gradle plugin can properly resolve it
    val onPhone = System.getenv("SDK_NAME")?.startsWith("iphoneos")?:false
    if(onPhone){
        iosArm64("ios")
    }else{
        iosX64("ios")
    }
    targets.getByName<KotlinNativeTarget>("ios").compilations["main"].kotlinOptions.freeCompilerArgs += "-Xobjc-generics"

    version = "1.0"

    sourceSets["commonMain"].dependencies {
        implementation(kotlin("stdlib-common", Versions.kotlin))
        implementation(Deps.klock)
        ...
    }
    ...
}
```

**Comment by PerrigoGames** [comment]
For now, I'm going to try to run it back to 1.9 since I've been having some issues with Kotlin 1.3.70.  I may have been misinterpreting the error and assuming that I was USING 1.3.70 rather than that version of klock LOOKING for 1.3.70.

**Comment by PerrigoGames** [comment]
Ran it back to 1.8.4 and that got me through.  I'll tackle the 1.3.70 update somewhere down the line.
