### ISSUE TITLE
Dulicate class error on Android 

### ISSUE THREAD

**Issue by seka** [korlibs/klock#97]
Hello, Thanks for good library.
But I have a problems introduce Klock version 1.9.1 into our Kotlin multiplatform project.
My project is the following dependencies:

```
// SharedCode project
commonMain.dependencies {
    implementation "com.soywiz.korlibs.klock:klock:1.9.1"  
}

// Android project
dependencies {
    implementation "com.soywiz.korlibs.klock:klock-jvm:1.9.1"
}
```

And compilation failed with the above settings.
(This is a partial excerpt:)

```
Duplicate class com.soywiz.klock.Date found in modules jetified-klock-debug-runtime-debug.jar (com.soywiz.korlibs.klock:klock-android:1.9.1) and jetified-klock-jvm-1.9.1.jar (com.soywiz.korlibs.klock:klock-jvm:1.9.1)
Duplicate class com.soywiz.klock.Date$Companion found in modules jetified-klock-debug-runtime-debug.jar (com.soywiz.korlibs.klock:klock-android:1.9.1) and jetified-klock-jvm-1.9.1.jar (com.soywiz.korlibs.klock:klock-jvm:1.9.1)
...
```

Am I doing something wrong setting? How can I avoid the problem?
Thanks!

**Comment by seka** [comment]
@soywiz 
What is the status of this issue?
If it's difficult to tackle, I'll try removing klock-jvm as a dependency.

**Comment by soywiz** [comment]
Instead of:
```
// Android project
dependencies {
    implementation "com.soywiz.korlibs.klock:klock-jvm:1.9.1"
}
```

Have you tried?

```
// Android project
dependencies {
    implementation "com.soywiz.korlibs.klock:klock-android:1.9.1"
}
```

**Comment by seka** [comment]
@soywiz 
Thanks. I succeeded compile ; )
README.md written that you can use klock-jvm If you are using only Android.
what is this klock-android ?
